services:
  postgres:
    image: postgres:17-alpine
    container_name: user-management-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_POSTGRES_PORT}:5432

volumes:
  postgres_data:
    driver: local
